[32mINFO    [0m test_02_home:test_02_home.py:18 ---测试我的个人主页---
[32mINFO    [0m test_02_home:base_page.py:37 点击元素：('id', 'com.dangdang.reader:id/tab_personal_rl')
[32mINFO    [0m test_02_home:base_page.py:37 点击元素：('id', 'com.dangdang.reader:id/common_menu_btn')
[32mINFO    [0m test_02_home:base_page.py:179 向上滑动第1次
[32mINFO    [0m test_02_home:base_page.py:134 等待：1s
[32mINFO    [0m test_02_home:base_page.py:179 向上滑动第2次
[32mINFO    [0m test_02_home:base_page.py:134 等待：1s
[31m[1mERROR   [0m test_02_home:settings_page.py:39 用户可能未登录！请先登录！
[32mINFO    [0m test_02_home:base_page.py:37 点击元素：('id', 'com.dangdang.reader:id/common_back')
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:749 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /wd/hub/session/01cf4c25-4fe2-4ea3-b534-f41ef4deb53e