{"uuid": "71b0c294-d980-4c0b-b911-f47097c0723d", "children": ["f9c41366-4486-411f-bbcc-a26086988293"], "befores": [{"name": "driver", "status": "passed", "start": 1587642292902, "stop": 1587642321238}], "afters": [{"name": "driver::end", "status": "broken", "statusDetails": {"message": "TypeError: '../test_result/report/allure_report' is not a valid filepath\n", "trace": "  File \"/Users/hehuaimei/PycharmProjects/appium/venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/hehuaimei/PycharmProjects/python_appium/appium_po/conftest.py\", line 38, in end\n    send_mail(\"../test_result/report/allure_report\")\n  File \"/Users/hehuaimei/PycharmProjects/python_appium/appium_po/conftest.py\", line 80, in send_mail\n    yag.send([\"hehuaimei@dangdang.com\",\"hehuaimei123@163.com\"],subject,contents,attachment)\n  File \"/Users/hehuaimei/PycharmProjects/appium/venv/lib/python3.8/site-packages/yagmail/sender.py\", line 148, in send\n    recipients, msg_string = self.prepare_send(\n  File \"/Users/hehuaimei/PycharmProjects/appium/venv/lib/python3.8/site-packages/yagmail/sender.py\", line 118, in prepare_send\n    msg = prepare_message(\n  File \"/Users/hehuaimei/PycharmProjects/appium/venv/lib/python3.8/site-packages/yagmail/message.py\", line 27, in prepare_message\n    raise TypeError(\"'{0}' is not a valid filepath\".format(a))\n"}, "start": 1587642357917, "stop": 1587642364569}], "start": 1587642292902, "stop": 1587642364569}